name: Production Deployment

on:
  push:
    branches:
      - master  # ✅ Only triggers on merge into master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: cicd-457416
          install_components: 'beta'

      - name: Build Docker image
        run: |
          docker build -t gcr.io/cicd-457416/cicd-app .

      - name: Push to Google Container Registry
        run: |
          docker push gcr.io/cicd-457416/cicd-app

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cicd-app \
            --image gcr.io/cicd-457416/cicd-app \
            --platform managed \
            --region asia-east1 \
            --allow-unauthenticated
